### ISSUE TITLE
How to implement "undrag"

### ISSUE THREAD

**Issue by brasilikum** [andrewMacmurray/seeds-game#57]
I find myself sometimes swiping the seed so I cannot complete a square and I think it would be nice if you could "undrag" seeds by swiping backwards in reverse order.

I checked out the codebase and was pretty overwhelmed how I would implement such a feature, even though it seems very nicely organized and well named. I am lacking experience with big elm codebases. Could you maybe tell me how you would start such a feature to see if I can figure it out?

**Comment by andrewMacmurray** [comment]
I'm actually part way through this feature at the moment on this branch - https://github.com/andrewMacmurray/seeds-game/tree/burst here's the bit where the magic happens https://github.com/andrewMacmurray/seeds-game/blob/burst/src/elm/Data/Board/Move/Check.elm#L24.

That bit of the codebase is particularly complicated (it was stuff I did very early on so it's definitely more complicated than it needs to be!) - trying simplify it and make it easier to understand.

I've not worked on seeds for a little while but planning to come back to it soon!

**Comment by brasilikum** [comment]
Interesting! That was roughly where I was looking. Happy to hear it's underway
